version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./:/app

  frontend:
    build: ./langflow/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./langflow/frontend:/app
    # Set process.env.BACKEND to the backend service
    environment:
      - BACKEND=http://backend:5003
