version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./:/app
    command: bash -c "uvicorn langflow.main:app --host 0.0.0.0 --port 7860 --reload"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
    # Set process.env.BACKEND to the backend service
    environment:
      - BACKEND_HOST="http://backend"
      - BACKEND_PORT="7860"
    restart: on-failure
