version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./:/app
    command: bash -c "uvicorn langflow.main:app --host 0.0.0.0 --port 5003 --reload"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ./dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
    # Set process.env.BACKEND to the backend service
    environment:
      - BACKEND="http://backend:5003"
