[tool.poetry]
name = "langflow"
version = "0.0.1"
description = "A Python package with a built-in web application"
authors = ["Ibis Prevedello <ibiscp@gmail.com>", "Gabriel Almeida <gabrielf.almeida90@gmail.com>"]
packages = [
    { include = "langflow"}
]
include = ["langflow/frontend/build/*", "langflow/frontend/build/**/*"]
exclude = ["langflow/frontend/node_modules/*", "langflow/frontend/src/*"]

[tool.poetry.scripts]
langflow = "langflow.cli:main"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.254"
black = "^23.1.0"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.9"
langflow_backend = {path = "langflow/backend"}
typer = "^0.7.0"