[tool.poetry]
name = "expert-backend"
version = "0.1.0"
description = ""
authors = ["Ibis Prevedello <ibiscp@gmail.com>"]
readme = "README.md"
packages = [{include = "expert_backend"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.26.5"
fastapi = "^0.91.0"
langchain = {path = "../langchain", develop = true}
uvicorn = "^0.20.0"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
