[tool.poetry]
name = "langflow"
version = "0.0.1"
description = "A Python package with a built-in web application"
authors = ["Ibis Prevedello <ibiscp@gmail.com>"]
packages = [
    { include = "langflow"}
]
include = ["langflow/frontend/build/*", "langflow/frontend/build/**/*"]
exclude = ["langflow/frontend/node_modules/*", "langflow/frontend/src/*"]

[tool.poetry.scripts]
langflow = "langflow.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.26.5"
fastapi = "^0.91.0"
uvicorn = "^0.20.0"
beautifulsoup4 = "^4.11.2"
google-search-results = "^2.4.1"
google-api-python-client = "^2.79.0"
langchain = {git = "https://github.com/ibiscp/langchain.git", rev = "ibis"}
typer = "^0.7.0"