chains:
  - LLMChain
  - LLMMathChain
  - LLMChecker
  # - ConversationChain

agents:
  - ZeroShotAgent

prompts:
  - PromptTemplate
  - FewShotPromptTemplate

llms:
  - OpenAI
  - OpenAIChat

tools:
  - Search
  - PAL-MATH
  - Calculator
  - Serper Search
  - Tool
  - PythonFunction

memories:
  # - ConversationBufferMemory

embeddings:
  #

vectorstores:
  #

documentloaders:
  #

dev: false
