agents:
  ZeroShotAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent"
  JsonAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/toolkits/openapi"
  CSVAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/toolkits/csv"
  AgentInitializer:
    documentation: "https://python.langchain.com/docs/modules/agents/agent_types/"
  VectorStoreAgent:
    documentation: ""
  VectorStoreRouterAgent:
    documentation: ""
  SQLAgent:
    documentation: ""
chains:
  LLMChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/llm_chain"
  LLMMathChain:
    documentation: "https://python.langchain.com/docs/modules/chains/additional/llm_math"
  LLMCheckerChain:
    documentation: "https://python.langchain.com/docs/modules/chains/additional/llm_checker"
  ConversationChain:
    documentation: ""
  SeriesCharacterChain:
    documentation: ""
  MidJourneyPromptChain:
    documentation: ""
  TimeTravelGuideChain:
    documentation: ""
  SQLDatabaseChain:
    documentation: ""
  RetrievalQA:
    documentation: "https://python.langchain.com/docs/modules/chains/popular/vector_db_qa"
  RetrievalQAWithSourcesChain:
    documentation: ""
  ConversationalRetrievalChain:
    documentation: "https://python.langchain.com/docs/modules/chains/popular/chat_vector_db"
  CombineDocsChain:
    documentation: ""
documentloaders:
  AirbyteJSONLoader:
    documentation: ""
  CoNLLULoader:
    documentation: ""
  CSVLoader:
    documentation: ""
  UnstructuredEmailLoader:
    documentation: ""
  EverNoteLoader:
    documentation: ""
  FacebookChatLoader:
    documentation: ""
  GutenbergLoader:
    documentation: ""
  BSHTMLLoader:
    documentation: ""
  UnstructuredHTMLLoader:
    documentation: ""
  UnstructuredMarkdownLoader:
    documentation: ""
  PyPDFLoader:
    documentation: ""
  UnstructuredPowerPointLoader:
    documentation: ""
  SRTLoader:
    documentation: ""
  TelegramChatLoader:
    documentation: ""
  TextLoader:
    documentation: ""
  UnstructuredWordDocumentLoader:
    documentation: ""
  WebBaseLoader:
    documentation: ""
  AZLyricsLoader:
    documentation: ""
  CollegeConfidentialLoader:
    documentation: ""
  HNLoader:
    documentation: ""
  IFixitLoader:
    documentation: ""
  IMSDbLoader:
    documentation: ""
  GitbookLoader:
    documentation: ""
  ReadTheDocsLoader:
    documentation: ""
  SlackDirectoryLoader:
    documentation: ""
  NotionDirectoryLoader:
    documentation: ""
  DirectoryLoader:
    documentation: ""
  GitLoader:
    documentation: ""
embeddings:
  OpenAIEmbeddings:
    documentation: ""
  HuggingFaceEmbeddings:
    documentation: ""
  CohereEmbeddings:
    documentation: ""
llms:
  OpenAI:
    documentation: ""
  ChatOpenAI:
    documentation: ""
  LlamaCpp:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp"
  CTransformers:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/ctransformers"
  Cohere:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/cohere"
  Anthropic:
    documentation: ""
  ChatAnthropic:
    documentation: ""
  HuggingFaceHub:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_hub"
memories:
  ConversationBufferMemory:
    documentation: "https://python.langchain.com/docs/modules/memory/how_to/summary"
  ConversationSummaryMemory:
    documentation: "https://python.langchain.com/docs/modules/memory/how_to/summary"
  ConversationKGMemory:
    documentation: "https://python.langchain.com/docs/modules/memory/how_to/kg"
  ConversationBufferWindowMemory:
    documentation: "https://python.langchain.com/docs/modules/memory/how_to/buffer_window"
  VectorStoreRetrieverMemory:
    documentation: "https://python.langchain.com/docs/modules/memory/how_to/vectorstore_retriever_memory"
prompts:
  PromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/"
  ZeroShotPrompt:
    documentation: "https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent"
textsplitters:
  CharacterTextSplitter:
    documentation: "https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/character_text_splitter"
  RecursiveCharacterTextSplitter:
    documentation: "https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter"
toolkits:
  OpenAPIToolkit:
    documentation: ""
  JsonToolkit:
    documentation: ""
  VectorStoreInfo:
    documentation: ""
  VectorStoreRouterToolkit:
    documentation: ""
  VectorStoreToolkit:
    documentation: ""
tools:
  Search:
    documentation: ""
  PAL-MATH:
    documentation: ""
  Calculator:
    documentation: ""
  Serper Search:
    documentation: ""
  Tool:
    documentation: ""
  PythonFunctionTool:
    documentation: ""
  PythonFunction:
    documentation: ""
  JsonSpec:
    documentation: ""
  News API:
    documentation: ""
  TMDB API:
    documentation: ""
  Podcast API:
    documentation: ""
  QuerySQLDataBaseTool:
    documentation: ""
  InfoSQLDatabaseTool:
    documentation: ""
  ListSQLDatabaseTool:
    documentation: ""
  BingSearchRun:
    documentation: ""
  GoogleSearchRun:
    documentation: ""
  GoogleSearchResults:
    documentation: ""
  GoogleSerperRun:
    documentation: ""
  JsonListKeysTool:
    documentation: ""
  JsonGetValueTool:
    documentation: ""
  PythonREPLTool:
    documentation: ""
  PythonAstREPLTool:
    documentation: ""
  RequestsGetTool:
    documentation: ""
  RequestsPostTool:
    documentation: ""
  RequestsPatchTool:
    documentation: ""
  RequestsPutTool:
    documentation: ""
  RequestsDeleteTool:
    documentation: ""
  WikipediaQueryRun:
    documentation: ""
  WolframAlphaQueryRun:
    documentation: ""
utilities:
  BingSearchAPIWrapper:
    documentation: ""
  GoogleSearchAPIWrapper:
    documentation: ""
  GoogleSerperAPIWrapper:
    documentation: ""
  SearxResults:
    documentation: ""
  SearxSearchWrapper:
    documentation: ""
  SerpAPIWrapper:
    documentation: ""
  WikipediaAPIWrapper:
    documentation: ""
  WolframAlphaAPIWrapper:
    documentation: ""
vectorstores:
  Chroma:
    documentation: ""
  Qdrant:
    documentation: ""
  Weaviate:
    documentation: ""
  FAISS:
    documentation: ""
  Pinecone:
    documentation: ""
  SupabaseVectorStore:
    documentation: ""
  MongoDBAtlasVectorSearch:
    documentation: ""
wrappers:
  RequestsWrapper:
    documentation: ""
