name: test-push

on:
  workflow_dispatch:


jobs:
  trigger-image-push-lc-serve:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build and push on langchain-serve
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEEPANKAR_GITHUB_TOKEN }}
          repository: jina-ai/langchain-serve
          event-type: langflow-push
          client-payload: '{"push_token": "${{ secrets.LCSERVE_PUSH_TOKEN }}", "branch": "dev"}'
